spring:
  datasource:
    url: ${ORACLE_URL}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  liquibase:
    contexts: prod

logging:
  level:
    com.example.kyc: INFO
    org.springframework: WARN
